<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\02-Infrastructure\LicenseGuard.Infrastructure.EFCore\LicenseGuard.Infrastructure.EFCore.csproj" />
    <ProjectReference Include="..\..\02-Infrastructure\LicenseGuard.Infrstructure.SecurityService\LicenseGuard.Infrstructure.SecurityService.csproj" />
    <ProjectReference Include="..\..\02-Infrastructure\LicenseGuard.Infrastructure.JwtService\LicenseGuard.Infrastructure.JwtService.csproj" />
    <ProjectReference Include="..\..\03-Application\LicenseGuard.Application\LicenseGuard.Application.csproj" />
  </ItemGroup>

</Project>
